# Generated by Django 4.2.7 on 2026-03-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AluminumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('length_mm', models.IntegerField(verbose_name='Длина, мм')),
                ('price_per_piece', models.FloatField(verbose_name='Цена за шт, руб')),
                ('joint_type_code', models.CharField(blank=True, max_length=10, verbose_name='Код узла (для автосчёта)')),
                ('count_per_joint', models.FloatField(default=1, verbose_name='Кол-во профилей на 1 узел')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Профиль алюминиевый',
                'verbose_name_plural': 'Профили алюминиевые',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделки')),
                ('price_sqm', models.FloatField(verbose_name='Цена руб/кв.м')),
            ],
            options={
                'verbose_name': 'Отделка',
                'verbose_name_plural': 'Отделки',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinishGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа отделки',
                'verbose_name_plural': 'Группы отделок',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код узла')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('offset_mm', models.FloatField(default=0, verbose_name='Поправка к ширине, мм')),
                ('price_per_meter', models.FloatField(default=0, verbose_name='Цена обработки руб/пм')),
                ('profile_article', models.CharField(blank=True, max_length=50, verbose_name='Артикул профиля')),
                ('profile_count', models.FloatField(default=0, verbose_name='Кол-во профилей на 1 узел')),
            ],
            options={
                'verbose_name': 'Тип узла',
                'verbose_name_plural': 'Типы узлов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО заказчика')),
                ('agent_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО агента')),
                ('counterparty', models.CharField(blank=True, max_length=300, verbose_name='Контрагент')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заказа')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия заказа')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название цвета')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Цвет профиля',
                'verbose_name_plural': 'Цвета профилей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, verbose_name='Порядковый №')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество, шт')),
                ('height_mm', models.FloatField(default=0, verbose_name='Высота, мм')),
                ('width_mm', models.FloatField(default=0, verbose_name='Ширина, мм')),
                ('decor_name', models.CharField(blank=True, max_length=300, verbose_name='Наименование декора 3D / направление шпона')),
                ('aluminum_vertical_count', models.IntegerField(default=0, verbose_name='Кол-во вертикального алюм. декора, шт')),
                ('aluminum_horizontal_count', models.IntegerField(default=0, verbose_name='Кол-во горизонтального алюм. декора, шт')),
                ('markup_percent', models.FloatField(default=0, verbose_name='Наценка, %')),
                ('notes', models.TextField(blank=True)),
                ('aluminum_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.profilecolor', verbose_name='Цвет алюм. декора')),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.finish', verbose_name='Отделка')),
                ('finish_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.finishgroup', verbose_name='Группа отделок')),
                ('joint_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Тип узла — низ')),
                ('joint_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Тип узла — левый край')),
                ('joint_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Тип узла — правый край')),
                ('joint_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Тип узла — верх')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='panels.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Стеновая панель',
                'verbose_name_plural': 'Стеновые панели',
                'ordering': ['order', 'position'],
            },
        ),
        migrations.AddField(
            model_name='finish',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishes', to='panels.finishgroup', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='DoorPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, verbose_name='Порядковый №')),
                ('door_order_number', models.CharField(blank=True, max_length=100, verbose_name='№ заказа дверного полотна из DGV')),
                ('opening_width', models.FloatField(default=0, verbose_name='Ширина проёма L, мм')),
                ('opening_height', models.FloatField(default=0, verbose_name='Высота проёма H, мм')),
                ('ceiling_height', models.FloatField(default=0, verbose_name='Высота потолка, мм')),
                ('mount_type', models.CharField(choices=[('ceiling', 'В потолок'), ('opening', 'В проём')], default='ceiling', max_length=20, verbose_name='Тип монтажа двери')),
                ('opening_direction', models.CharField(choices=[('in', 'Внутрь'), ('out', 'Наружу')], default='in', max_length=10, verbose_name='Открывание двери')),
                ('panel_height', models.FloatField(default=0, verbose_name='Высота панели над дверью, мм')),
                ('panel_width', models.FloatField(default=0, verbose_name='Ширина панели над дверью, мм')),
                ('decor_name', models.CharField(blank=True, max_length=300, verbose_name='Наименование декора 3D / направление шпона')),
                ('notes', models.TextField(blank=True)),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.finish', verbose_name='Отделка')),
                ('finish_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panels.finishgroup', verbose_name='Группа отделок')),
                ('joint_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Узел соединения с дверной коробкой (нижний)')),
                ('joint_top_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Узел соединения панелей над дверью (левый)')),
                ('joint_top_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Узел соединения панелей над дверью (правый)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_panels', to='panels.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Панель над дверью',
                'verbose_name_plural': 'Панели над дверями',
                'ordering': ['order', 'position'],
            },
        ),
    ]
