# Generated by Django 5.2.12 on 2026-04-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='decor_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Группа декора'),
        ),
        migrations.AddField(
            model_name='panel',
            name='veneer_direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Направление шпона'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='decor_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Наименование декора 3D'),
        ),
    ]
