# Generated by Django 5.2.12 on 2026-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_add_veneer_direction_and_decor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorpanel',
            name='wall_number',
            field=models.CharField(default='1', max_length=50, verbose_name='Номер стены'),
        ),
        migrations.AddField(
            model_name='panel',
            name='wall_number',
            field=models.CharField(default='1', max_length=50, verbose_name='Номер стены'),
        ),
    ]
