# Generated by Django 5.2.12 on 2026-04-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_add_wall_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorpanel',
            name='edge_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Кромка левая'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='edge_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Кромка правая'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='edge_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Кромка верхняя'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='veneer_direction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Направление шпона'),
        ),
        migrations.AlterField(
            model_name='doorpanel',
            name='decor_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Наименование декора 3D'),
        ),
    ]
