# Generated by Django 5.2.12 on 2026-04-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_add_door_edges_veneer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorpanel',
            name='edge_bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panels.jointtype', verbose_name='Кромка нижняя'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='markup_percent',
            field=models.FloatField(default=0, verbose_name='Наценка, %'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество, шт'),
        ),
    ]
