# Generated by Django 5.2.12 on 2026-04-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0008_jointtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='configurator_state',
            field=models.JSONField(blank=True, null=True, verbose_name='Состояние конфигуратора'),
        ),
    ]
