# Generated by Django 5.2.12 on 2026-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0009_order_configurator_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorpanel',
            name='cascate_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='id в cascate.ru'),
        ),
        migrations.AddField(
            model_name='doorpanel',
            name='cascate_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выгружена в cascate.ru'),
        ),
        migrations.AddField(
            model_name='order',
            name='cascate_id_person',
            field=models.CharField(blank=True, max_length=64, verbose_name='id_person в cascate.ru'),
        ),
        migrations.AddField(
            model_name='order',
            name='cascate_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выгружен в cascate.ru'),
        ),
        migrations.AddField(
            model_name='panel',
            name='cascate_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='id в cascate.ru'),
        ),
        migrations.AddField(
            model_name='panel',
            name='cascate_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выгружена в cascate.ru'),
        ),
    ]
