# Generated by Django 5.2.12 on 2026-07-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0010_doorpanel_cascate_id_doorpanel_cascate_synced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название цвета')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Обрамление: цвет профиля',
                'verbose_name_plural': 'Обрамление: цвета профилей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FramingDoborGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('is_dobor', models.BooleanField(default=True, verbose_name='Доступна как добор')),
                ('is_glass', models.BooleanField(default=False, verbose_name='Доступна как вставка')),
                ('glass_price_per_m', models.FloatField(default=620, verbose_name='Цена вставки, руб/м')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Обрамление: группа отделок',
                'verbose_name_plural': 'Обрамление: группы отделок',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FramingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('buyer', models.CharField(blank=True, max_length=300, verbose_name='Покупатель')),
                ('note', models.TextField(blank=True, verbose_name='Примечание к спецификации')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('install', models.CharField(blank=True, max_length=50, verbose_name='Установка')),
                ('kit', models.CharField(blank=True, max_length=20, verbose_name='Комплектация')),
                ('opening_height', models.FloatField(default=0, verbose_name='Высота проёма')),
                ('opening_width', models.FloatField(default=0, verbose_name='Ширина проёма')),
                ('wall_depth', models.FloatField(default=0, verbose_name='Глубина стены')),
                ('color_name', models.CharField(blank=True, max_length=200, verbose_name='Цвет наличника')),
                ('dobor_name', models.CharField(blank=True, max_length=200, verbose_name='Отделка добора')),
                ('glass', models.CharField(blank=True, max_length=300, verbose_name='Вставка')),
                ('spec', models.JSONField(blank=True, null=True, verbose_name='Спецификация (строки)')),
                ('total', models.FloatField(default=0, verbose_name='Итого, руб')),
            ],
            options={
                'verbose_name': 'Обрамление: заявка',
                'verbose_name_plural': 'Обрамление: заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FramingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('nH', models.FloatField(default=0, verbose_name='Поправка высоты наличника')),
                ('nL', models.FloatField(default=0, verbose_name='Поправка ширины наличника')),
                ('dH', models.FloatField(default=0, verbose_name='Поправка высоты добора')),
                ('dL', models.FloatField(default=0, verbose_name='Поправка ширины добора')),
                ('depth_mode', models.CharField(choices=[('luna', 'Luna (C + 10/5)'), ('cas', 'Cascade (= C)'), ('fixed', 'Фикс. поправка (C + delta)')], default='fixed', max_length=10, verbose_name='Расчёт глубины добора')),
                ('depth_delta', models.FloatField(default=0, verbose_name='Поправка глубины (для fixed)')),
                ('profile_count', models.IntegerField(default=4, verbose_name='Кол-во профилей')),
                ('has_glass', models.BooleanField(default=False, verbose_name='Со вставкой (стекло/зеркало)')),
                ('price_category', models.CharField(choices=[('mini', 'MINI'), ('passo', 'PASSO'), ('triangle', 'TRIANGLE'), ('default', 'Стандарт')], default='default', max_length=20, verbose_name='Категория цены профиля')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Обрамление: модель',
                'verbose_name_plural': 'Обрамление: модели',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FramingProfilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mini', 'MINI'), ('passo', 'PASSO'), ('triangle', 'TRIANGLE'), ('default', 'Стандарт')], max_length=20, unique=True, verbose_name='Категория профиля')),
                ('price_per_3000', models.FloatField(verbose_name='Цена за 3000 мм, руб')),
            ],
            options={
                'verbose_name': 'Обрамление: цена профиля',
                'verbose_name_plural': 'Обрамление: цены профилей',
            },
        ),
        migrations.CreateModel(
            name='FramingDobor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена, руб/кв.м')),
                ('sort_order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dobors', to='panels.framingdoborgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Обрамление: отделка добора',
                'verbose_name_plural': 'Обрамление: отделки добора',
                'ordering': ['group', 'sort_order', 'id'],
            },
        ),
    ]
