# Generated by Django 5.2.12 on 2026-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0011_framingcolor_framingdoborgroup_framinglead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jointtype',
            options={'ordering': ['series', 'code'], 'verbose_name': 'Тип узла', 'verbose_name_plural': 'Типы узлов'},
        ),
        migrations.AddField(
            model_name='finishgroup',
            name='series',
            field=models.CharField(choices=[('50', 'NUOVO 50'), ('60', 'NUOVO 60')], default='60', max_length=2, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='jointtype',
            name='series',
            field=models.CharField(choices=[('50', 'NUOVO 50'), ('60', 'NUOVO 60')], default='60', max_length=2, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='order',
            name='series',
            field=models.CharField(choices=[('50', 'NUOVO 50'), ('60', 'NUOVO 60')], default='60', max_length=2, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='finishgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='jointtype',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код узла'),
        ),
        migrations.AlterUniqueTogether(
            name='finishgroup',
            unique_together={('name', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='jointtype',
            unique_together={('code', 'series')},
        ),
    ]
