# Generated by Django 5.2.12 on 2026-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0012_alter_jointtype_options_finishgroup_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framingmodel',
            name='has_shadow',
            field=models.BooleanField(default=False, verbose_name='С теневым профилем'),
        ),
        migrations.AddField(
            model_name='framingmodel',
            name='has_veneer',
            field=models.BooleanField(default=False, verbose_name='Доступен наличник со шпоном'),
        ),
        migrations.AddField(
            model_name='framingmodel',
            name='shadow_nH',
            field=models.FloatField(default=0, verbose_name='Поправка высоты теневого профиля'),
        ),
        migrations.AddField(
            model_name='framingmodel',
            name='shadow_nL',
            field=models.FloatField(default=0, verbose_name='Поправка ширины теневого профиля'),
        ),
        migrations.AddField(
            model_name='framingmodel',
            name='shadow_price_per_m',
            field=models.FloatField(default=1200, verbose_name='Цена теневого профиля, руб/м пог'),
        ),
        migrations.AddField(
            model_name='framingmodel',
            name='veneer_surcharge',
            field=models.FloatField(default=800, verbose_name='Надбавка за шпон, руб/м пог'),
        ),
    ]
