# Generated by Django 5.2.12 on 2026-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0015_regroup_finishes_by_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='framinglead',
            name='cascate_id_person',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id_person в cascate.ru'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cascate_id_person',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id_person в cascate.ru'),
        ),
    ]
