# Generated by Django 5.2.12 on 2026-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0016_framinglead_cascate_id_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('id_person', models.CharField(db_index=True, max_length=64, verbose_name='id_person в cascate.ru')),
                ('login', models.CharField(blank=True, max_length=200, verbose_name='Логин')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия cascate.ru',
                'verbose_name_plural': 'Сессии cascate.ru',
                'ordering': ['-last_seen'],
            },
        ),
    ]
