# Generated by Django 5.2.12 on 2026-10-06 06:38

from django.db import migrations, models


XL_MODELS = ['Luna', 'Luna-Glass', 'Dune', 'Cascade']


def mark_xl(apps, schema_editor):
    apps.get_model('panels', 'FramingModel').objects.filter(name__in=XL_MODELS).update(xl_price=True)


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0018_joint_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='framingmodel',
            name='xl_price',
            field=models.BooleanField(default=False, verbose_name='Цена по заводскому Excel (Luna/Dune/Cascade)'),
        ),
        migrations.RunPython(mark_xl, migrations.RunPython.noop),
    ]
